name: ISSUE
description: Address something that needs to be done
title: ISSUE - 
labels: issue
body:
- type: markdown
  attributes:
    value: "hi!"
- type: checkboxes
  id: problems
  attributes:
    label: What is the problem associated with?
    options:
    - label: Command
    - label: Connection
    - label: Gameplay
    - label: Discord
    - label: Github
    - label: Website
- type: textarea
  id: repro
  attributes:
    label: Reproduction steps
    description: "Explain the issue"
    value: go crazy!
    render: bash
  validations:
    required: true
