---
name: Recovery Request
description: request for chunks or player inventories to be individually rolled back
labels: Rollbacks
title: Rollback
body:
- type: input
  attributes:
    label: coordinates for admin to visit
    placeholder: <x>, <y>, <z>

- type: input
  attributes:
    label: time to roll back to (EDT)
    placeholder: 7:36 PM, September 4, 2023
  validations:
    required: true
    
---
