name: TODO
description: Address something that needs to be done
title: TODO - 
labels: issue
body:
- type: markdown
  attributes:
    value: "hi!"
- type: checkboxes
  id: problems
  attributes:
    label: what d?
    options:
      - label: Command
      - label: Connection
      - label: Gameplay
      - label: Discord
      - label: Github
      - label: Website
      - label: Resource Pack
      - label: Data Pack
- type: textarea
  id: repro
  attributes:
    label: Task
    description: "Describe the task"
    value: write something down!!!
    render: markdown
  validations:
  - required: true
