name: TODO
description: Address something that needs to be done
title: TODO - 
labels: "help wanted"
body:
- type: markdown
  attributes:
    value: "hi!"
- type: checkboxes
  id: problems
  attributes:
    label: CATEGORIES
    options:
      - label: Command
      - label: Connection
      - label: Gameplay
      - label: Discord
      - label: Github
      - label: Website
      - label: Resource Pack
      - label: Data Pack
- type: textarea
  id: repro
  attributes:
    label: Reproduction steps
    description: "Enter text"
    value: |
      1.
      2.
      3.
      ...
    render: bash
  validations:
    required: true
