version: "3.8"

services:
  vanilla:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      MEMORY: "8G"
      EULA: "TRUE"
      MOTD: "1.20.2 Vanilla
       https://discord.gg/YqbRQdS2Qc"
    volumes:
      - ./vanilla:/data
volumes:
  vanilla:
    external: true