version: "3.8"

services:
  vanilla:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      MEMORY: "4G"
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      
      MOTD: "\u00a7c\u00a7lG\u00a76\u00a7lou\u00a7e\u00a7lr\u00a72\u00a7lm\u00a7a\u00a7le\u00a73\u00a7lt\u00a7b\u00a7l S\u00a79\u00a7le\u00a71\u00a7lr\u00a75\u00a7lv\u00a7d\u00a7le\u00a7r\u00a7lr\u00a7r\ndiscord.gg\/6BM2dn2sja"
    volumes:
      - ./vanilla:/data
volumes:
  vanilla:
    external: true